Path 2
dotnepal/blood-donors pull request #17
Opened 2016-10-10 03:26 UTC by bravegurkha

Routes added

2016-10-10 05:41 UTC, samundra commented on resources/views/layouts/app.blade.php
> +                    <ul class="nav navbar-nav navbar-right">
create navigation template partial.

2016-10-10 05:44 UTC, samundra requested changes
Please address the comments

2016-10-10 05:44 UTC, samundra commented on resources/views/layouts/app.blade.php
> +    <script src="/js/app.js"></script>
use elixir

2016-10-10 05:44 UTC, samundra commented on routes/web.php
> +Auth::routes();
use auth middleware don't define route yourself for it.

2016-10-10 05:44 UTC, samundra commented on resources/views/auth/passwords/email.blade.php
> +                                    Send Password Reset Link
use translations

2016-10-10 05:44 UTC, samundra commented on resources/views/auth/passwords/email.blade.php
> +                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>
use translations

2016-10-10 05:44 UTC, samundra commented on resources/views/auth/passwords/email.blade.php
> +                <div class="panel-heading">Reset Password</div>
use translations

2016-10-10 05:44 UTC, samundra commented on app/Http/Controllers/HomeController.php
> +        $this->middleware('auth');
use auth middleware in the route, don't use here.

2016-10-10 05:47 UTC, bravegurkha commented on resources/views/layouts/app.blade.php
> +                    <ul class="nav navbar-nav navbar-right">
Do you mean adding creating one .blade.php file for navigation?

2016-10-12 06:50 UTC, samundra commented
Please commit changes into separate PRs. That way it's easier to rollback if need be and is more manageable.

2018-03-10 14:36 UTC, closed without merging