[Path 18] Migrations and Seeders for users, donors and receivers
dotnepal/blood-donors pull request #19
Opened 2016-10-10 13:29 UTC by bravegurkha

Done #18

2016-10-10 18:27 UTC, samundra commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->longText('address');
use `string` with fixed length.

2016-10-10 18:27 UTC, samundra commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->integer('user_type_id');
add reference to `user_type` table. as in `$table->foreign('user_id')->references('id')->on('users');`

2016-10-10 18:28 UTC, samundra commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('blood_group');
use `enum` we'll have fixed set of blood groups.

2016-10-10 18:29 UTC, samundra commented on app/Donations.php
> +{
enable `soft deletes`

2016-10-10 18:32 UTC, samundra commented on database/seeds/DonationsTableSeeder.php
> +      \App\Donations::create(
- use faker to seed data
- don't use Fully qualified class names. e.g. `\App\Donations`

```
use `App\Donations`;
```

2016-10-10 18:33 UTC, samundra commented on database/seeds/UsersTableSeeder.php
> +        'email' => 'srestaswrnm@gmail.com',
use [Faker Library](https://github.com/fzaninotto/Faker) to generate random data. There are faker formatter for Nepali names as well.

2016-10-10 18:34 UTC, samundra commented on database/seeds/UsersTableSeeder.php
> +        'phone' => '9818278249',
Big NO NO for using the real data. Please replace these with faker.

2016-10-10 18:35 UTC, samundra requested changes
Make the changes that I have mentioned

2016-10-11 17:50 UTC, samundra commented
Why `composer.lock` in commit ?

2016-10-11 17:58 UTC, bravegurkha commented
Ah! Installed Faker!

2016-10-15 02:44 UTC, samundra commented
@bravegurkha Please resolve the conflict

2016-10-15 02:48 UTC, samundra requested changes

2016-10-15 02:48 UTC, samundra commented on database/seeds/UsersTableSeeder.php
> +
remove blank line

2016-10-15 02:48 UTC, samundra commented on database/seeds/UsersTableSeeder.php
> +      \App\User::create(array(
use 4 spaces for indentation. Please fix the indentation through the PR and use `phpcs` to verify that it meets our coding standard.

2016-10-15 03:25 UTC, samundra requested changes

2016-10-15 03:25 UTC, samundra commented on app/UserDonation.php
> +    use SoftDelets;
typo mistake should be `SoftDeletes`

2016-10-15 10:07 UTC, samundra commented
Please fix the conflicts and address the comments

2017-01-09 19:43 UTC, samundra approved these changes

2017-01-09 19:43 UTC, samundra commented on .gitignore
> +>>>>>>> master
these are due to merge conflict, we dont' need these. remove them.

2017-01-09 19:44 UTC, merged